#pragma once

#define SEMATENA_NAMESPACE_BEGIN namespace Sematena {
#define SEMATENA_NAMESPACE_END }
#define SEMATENA_VIEWMODEL_NAMESPACE_BEGIN SEMATENA_NAMESPACE_BEGIN namespace ViewModel {
#define SEMATENA_VIEWMODEL_NAMESPACE_END SEMATENA_NAMESPACE_END }
#define SEMATENA_EXTENSIONS_NAMESPACE_BEGIN SEMATENA_NAMESPACE_BEGIN namespace XamlExtensions {
#define SEMATENA_EXTENSIONS_NAMESPACE_END SEMATENA_NAMESPACE_END }